name: ${APP_NAME_HOST}

networks:
  internal:
    name: ${APP_NAME_HOST}_internal
    driver: bridge
    ipam:
      config:
        - subnet: "${APP_NETWORK_POOL}"

volumes:
  habitat-config:
  traefik-certs:
  traefik-config:
  tailscale-state:
  tailscale-config:


secrets:
  TS_AUTHKEY:
    file: ${SECRETS_DIR}/TS_AUTHKEY
  PORKBUN_API_KEY:
    file: ${SECRETS_DIR}/PORKBUN_API_KEY
  PORKBUN_API_SECRET_KEY:
    file: ${SECRETS_DIR}/PORKBUN_API_SECRET_KEY

services:

  habitat-config-path:
    image: tschebbischeff/habitat-config:latest
    container_name: ${APP_NAME_HOST}_habitat-config-path
    restart: no
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/habitat-config.env
        required: false
    environment:
      MODULE_NAME: "path"
    networks:
      internal:
    volumes:
      - habitat-config:/habitat-config/orchestration
      - ./habitat-config:/habitat-config/source:ro
      - traefik-config:/habitat-config/target/traefik
      - tailscale-config:/habitat-config/target/tailscale

  traefik:
    build:
      context: ./traefik
    container_name: ${APP_NAME_HOST}_traefik
    restart: unless-stopped
    expose:
      - "80"
      - "443"
      - "8080"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/traefik.env
        required: false
    secrets:
      - PORKBUN_API_KEY
      - PORKBUN_API_SECRET_KEY
    volumes:
      - traefik-config:/etc/traefik
      - traefik-certs:/etc/traefik-certs
    networks:
      internal:
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      habitat-config-path:
        condition: service_completed_successfully

  tailscale:
    build:
      context: ./tailscale
    container_name: ${APP_NAME_HOST}_tailscale
    restart: unless-stopped
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/tailscale.env
        required: false
    environment:
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_USERSPACE: "true"
      TS_HOSTNAME: "${APP_NAME_HOST}"
      TS_ACCEPT_DNS: "false"
      TS_SERVE_CONFIG: "/config/serve-config.json"
      TS_ENABLE_HEALTH_CHECK: "true"
      TS_LOCAL_ADDR_PORT: "127.0.0.1:41234"
      TS_AUTH_ONCE: "true"
      TS_AUTHKEY_FILE: /run/secrets/TS_AUTHKEY
    secrets:
      - TS_AUTHKEY
    volumes:
      - tailscale-state:/var/lib/tailscale
      - tailscale-config:/config
    networks:
      internal:
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
